baseURL = "http://blog.ylitalot.com/"
title = "(Dev)Ops observations"
copyright = "Juha Ylitalo &lt;juha@ylitalot.net&gt;"

hasCJKLanguage = false
languageCode = "en"

theme = "hugo-theme-anubis"
paginate = 3
PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[menus]
  main = [
    {Name="Index", URL="/", Weight=1},
    {Name="About", URL="/about", Weight=100}
  ]
[params]
  author = "Juha Ylitalo"
  email = "juha@ylitalot.net"
  avatar = "/images/avatar.jpg"
  description = "Observations from working in public cloud environments"
  mainSections = ["post"]
  social = [
    {id = "email", url = "mailto:juha.ylitalo@gmail.com"},
    {id = "twitter", url = "https://twitter.com/jylitalo"},
    {id = "github", url = "https://github.com/jylitalo"},
  ]
  style = "auto"
